Coffee machine
DanilFilikov/CoffeeMachine pull request #1
Opened 2023-04-18 08:04 UTC by DanilFilikov

2023-04-18 09:20 UTC, MVlasovD requested changes

2023-04-18 09:20 UTC, MVlasovD commented on .gitignore.save
> +target/
странные гитигноры у тебя
и их два

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/Bosh.java
> +    public enum Coffee {
инам вынеси в отдельный класс

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/Bosh.java
> +/*    public void showAllProfiles(){
закомментированного кода не должно быть

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/Bosh.java
> +
много пустых строк
одной достаточно

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/Bosh.java
> +            }catch(Exception ignored){
пустой кэтч

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/Main.java
> +// Press Shift twice to open the Search Everywhere dialog and type `show whitespaces`,
комменты

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/Bosh.java
> +                System.out.println("""
по элсу возвращаешь практически одинаковое меню, можно вынести текст меню в отдельную переменную или метод

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/Bosh.java
> +    public void machineMenu() throws Exception {
зачем везде прокидывать 
throws Exception

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/Bosh.java
> +                throw new Exception("Кофемашина грязная!\n");
у тебя же приложение должно  упасть по исключению, а не должно

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/CoffeeMachine.java
> +public abstract class CoffeeMachine {
очень большой контракт у данного абстактного класса,
слишком много методов необходимо реализовать наследнику,
лучше разделить функциональность по разным классам

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/Bosh.java
> +        if (!IsOn()) { throw new Exception("Кофемашина не работает");
исключения будешь выбрасывать на каждое движение?

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/Bosh.java
> +    public void ingredientsLeft() throws Exception {
```suggestion
    public void getIngredients() throws Exception {
```

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/Bosh.java
> +    public void ingredientsCheck() throws Exception {
```suggestion
    public void checkIngredients() throws Exception {
```
называем методы по конвенции Java

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/Bosh.java
> +    public void cleanCheck() throws Exception {
```suggestion
    public void checkClean() throws Exception {
```

2023-04-18 09:20 UTC, MVlasovD commented on src/main/java/org/example/CoffeeMachine.java
> +    private short amount_of_coffee;
название переменных camelCase, не snake_case

2023-04-18 09:22 UTC, DanilFilikov commented on .gitignore.save
> +target/
да только сейчас увидел, не знаю откуда они взялись

2023-04-19 07:44 UTC, MVlasovD requested changes

2023-04-19 07:44 UTC, MVlasovD commented on src/main/java/org/example/domain/Bosh.java
> +            Log.i("Added coffee to the machine");
```suggestion
            Log.info("Added coffee to the machine");
```

2023-04-19 07:44 UTC, MVlasovD commented on src/main/java/org/example/domain/Bosh.java
> +                System.out.println("Нет такого напитка\n");
для этого можно использовать блок default у свитча

2023-04-19 07:44 UTC, MVlasovD commented on src/main/java/org/example/domain/CoffeeMachine.java
> +    public abstract void addWater() throws Exception;
контракт не особо уменьшился

2023-04-19 07:44 UTC, MVlasovD commented on src/main/java/org/example/domain/Log.java
> +    static void i(String message) {
метод с именем i ?

2023-04-19 07:44 UTC, MVlasovD commented on src/main/java/org/example/domain/Bosh.java
> +
```suggestion
```

2023-04-19 07:44 UTC, MVlasovD commented on src/main/java/org/example/domain/Bosh.java
> +
много пустых строк

2023-04-19 07:44 UTC, MVlasovD commented on src/main/java/org/example/domain/Bosh.java
> +        for (Coffee coffee: drinks) {
зачем здесь форич?
ты выводищь в консоль все равно drinks

2023-04-19 07:44 UTC, MVlasovD commented on .gitignore.save
> +target/
эти гитигноры удали

2023-04-21 12:46 UTC, MVlasovD approved these changes

2023-04-21 12:46 UTC, merged